spring:
  application:
    name: customerservice
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  profiles:
    active: qa
  config:
    import: optional:configserver:http://localhost:8071/

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: customerservice
    description: Online Food Delivery Customer Application
    version: 1.0



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      #access: unrestricted
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  info:
    env:
      enabled: true

logging:
  level:
    com:
      microservices: DEBUG




