spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true

info:
  app:
    name: gatewayserver
    description: Online Food Delivery Gateway Application
    version: 1.0



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

  info:
    env:
      enabled: true

logging:
  level:
    com:
      microservices: DEBUG




