server:
    port: 8081
spring:
  application:
    name: restaurantservice
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testrestaurant
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  profiles:
    active: qa
  config:
    import: optional:configserver:http://localhost:8071/

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: restaurantservice
    description: Online Food Delivery Restaurant Application
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      #access: unrestricted
      enabled: true

  info:
    env:
      enabled: true



