services:
  network-deploy-service:
    networks:
      - online-food-order-app-network

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700MB
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      SPRING_PROFILES_ACTIVE: qa
